services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P4ss_W0rd
      - MSSQL_TCP_PORT=1433
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "pgrep", "sqlservr"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
  
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672      # RabbitMQ
      - 15672:15672    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password